//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.27 at 01:07:39 PM CST
//


package duskz.map.io;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "properties",
    "tileset",
    "layerOrObjectgroup"
})
@XmlRootElement(name = "map")
public class Map {

    @XmlAttribute(name = "xmlns")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlns;
    @XmlAttribute(name = "xmlns:xsi")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlnsXsi;
    @XmlAttribute(name = "xsi:schemaLocation")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xsiSchemaLocation;
    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "orientation", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String orientation;
    @XmlAttribute(name = "width", required = true)
    protected int width;
    @XmlAttribute(name = "height", required = true)
    protected int height;
    @XmlAttribute(name = "tilewidth", required = true)
    protected int tilewidth;
    @XmlAttribute(name = "tileheight", required = true)
    protected int tileheight;
    protected Properties properties;
    protected List<Tileset> tileset;
    @XmlElements({
        @XmlElement(name = "layer", type = Layer.class),
        @XmlElement(name = "objectgroup", type = Objectgroup.class)
    })
    protected List<java.lang.Object> layerOrObjectgroup;

    /**
     * Gets the value of the xmlns property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXmlns() {
        return xmlns;
    }

    /**
     * Sets the value of the xmlns property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXmlns(String value) {
        this.xmlns = value;
    }

    /**
     * Gets the value of the xmlnsXsi property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXmlnsXsi() {
        return xmlnsXsi;
    }

    /**
     * Sets the value of the xmlnsXsi property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXmlnsXsi(String value) {
        this.xmlnsXsi = value;
    }

    /**
     * Gets the value of the xsiSchemaLocation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getXsiSchemaLocation() {
        return xsiSchemaLocation;
    }

    /**
     * Sets the value of the xsiSchemaLocation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setXsiSchemaLocation(String value) {
        this.xsiSchemaLocation = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the orientation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrientation(String value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the width property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWidth(int value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHeight(int value) {
        this.height = value;
    }

    /**
     * Gets the value of the tilewidth property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public int getTilewidth() {
        return tilewidth;
    }

    /**
     * Sets the value of the tilewidth property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTilewidth(int value) {
        this.tilewidth = value;
    }

    /**
     * Gets the value of the tileheight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public int getTileheight() {
        return tileheight;
    }

    /**
     * Sets the value of the tileheight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTileheight(int value) {
        this.tileheight = value;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return
     *     possible object is
     *     {@link Properties }
     *
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value
     *     allowed object is
     *     {@link Properties }
     *
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the tileset property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tileset property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTileset().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tileset }
     *
     *
     */
    public List<Tileset> getTileset() {
        if (tileset == null) {
            tileset = new ArrayList<Tileset>();
        }
        return this.tileset;
    }

    /**
     * Gets the value of the layerOrObjectgroup property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layerOrObjectgroup property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayerOrObjectgroup().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Layer }
     * {@link Objectgroup }
     *
     *
     */
    public List<java.lang.Object> getLayerOrObjectgroup() {
        if (layerOrObjectgroup == null) {
            layerOrObjectgroup = new ArrayList<java.lang.Object>();
        }
        return this.layerOrObjectgroup;
    }

}
