//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.27 at 01:07:39 PM CST
//


package duskz.map.io;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tileset }
     *
     */
    public Tileset createTileset() {
        return new Tileset();
    }

    /**
     * Create an instance of {@link Image }
     *
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Tile }
     *
     */
    public Tile createTile() {
        return new Tile();
    }

    /**
     * Create an instance of {@link Properties }
     *
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Objectgroup }
     *
     */
    public Objectgroup createObjectgroup() {
        return new Objectgroup();
    }

    /**
     * Create an instance of {@link Object }
     *
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link Data }
     *
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Map }
     *
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Layer }
     *
     */
    public Layer createLayer() {
        return new Layer();
    }

    /**
     * Create an instance of {@link Property }
     *
     */
    public Property createProperty() {
        return new Property();
    }

}
