//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.02.27 at 01:07:39 PM CST
//


package duskz.map.io;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "image",
    "tile"
})
@XmlRootElement(name = "tileset")
public class Tileset {

    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "firstgid", required = true)
    protected int firstgid;
    @XmlAttribute(name = "source")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String source;
    @XmlAttribute(name = "tilewidth")
    protected int tilewidth;
    @XmlAttribute(name = "tileheight")
    protected int tileheight;
    @XmlAttribute(name = "spacing")
    protected int spacing;
    @XmlAttribute(name = "margin")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String margin;
    protected List<Image> image;
    protected List<Tile> tile;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the firstgid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public int getFirstgid() {
        return firstgid;
    }

    /**
     * Sets the value of the firstgid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFirstgid(int value) {
        this.firstgid = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the tilewidth property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public int getTilewidth() {
        return tilewidth;
    }

    /**
     * Sets the value of the tilewidth property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTilewidth(int value) {
        this.tilewidth = value;
    }

    /**
     * Gets the value of the tileheight property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public int getTileheight() {
        return tileheight;
    }

    /**
     * Sets the value of the tileheight property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTileheight(int value) {
        this.tileheight = value;
    }

    /**
     * Gets the value of the spacing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public int getSpacing() {
        return spacing;
    }

    /**
     * Sets the value of the spacing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSpacing(int value) {
        this.spacing = value;
    }

    /**
     * Gets the value of the margin property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMargin() {
        return margin;
    }

    /**
     * Sets the value of the margin property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMargin(String value) {
        this.margin = value;
    }

    /**
     * Gets the value of the image property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Image }
     *
     *
     */
    public List<Image> getImage() {
        if (image == null) {
            image = new ArrayList<Image>();
        }
        return this.image;
    }

    /**
     * Gets the value of the tile property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tile property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTile().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tile }
     *
     *
     */
    public List<Tile> getTile() {
        if (tile == null) {
            tile = new ArrayList<Tile>();
        }
        return this.tile;
    }

}
